return {
	"SmiteshP/nvim-navic",
	opts = {
		icons = {
			Array = "󰅪 ",
			Boolean = "◩ ",
			Class = " ",
			Constant = "󰏿 ",
			Constructor = " ",
			Enum = "󰕘 ",
			EnumMember = " ",
			Event = " ",
			Field = "󰨔 ",
			File = "󰈙 ",
			Function = "󰊕 ",
			Interface = " ",
			Key = "󰌋 ",
			Method = "󰊕 ",
			Module = " ",
			Namespace = " ",
			Null = "󰟢 ",
			Number = "󰎠 ",
			Object = "󰅩 ",
			Operator = "󰆕 ",
			Package = " ",
			Property = " ",
			String = "󰀬 ",
			Struct = "󰌗 ",
			TypeParameter = "󰊄 ",
			Variable = "󰆧 ",
		},
		lsp = {
			auto_attach = true,
			preference = nil,
		},
		highlight = false,
		separator = " > ",
		depth_limit = 0,
		depth_limit_indicator = "..",
		safe_output = true,
		lazy_update_context = false,
		click = false,
		format_text = function(text)
			return text
		end,
	},
}
